# Generated by Django 6.0.4 on 2026-04-27 12:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150, verbose_name='Mahsulot nomi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Mahsulot narxi')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Mahsulot rasmi')),
                ('description', models.TextField(null=True, verbose_name='Mahsulot tarifi')),
                ('in_stock', models.IntegerField(default=1, verbose_name='Mavjud mahsulotlar')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_main.category')),
            ],
        ),
    ]
